#!/usr/bin/env python

# Removes temporary code under JUSTATEMPs globally
# in a git repo

# Copyright (C) 2014-2017  Author: Misha Orel
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import subprocess
import uuid

p = subprocess.Popen(["git", "grep", "JUSTATEMP"],
                     stdout=subprocess.PIPE,
                     stderr=subprocess.PIPE)
out, err = p.communicate()
lines = out.split("\n")

file_set = set()
for l in lines:
    index = l.find(":")
    if index != -1:
        file_set.add(l[0:index])

temp_fname = str(uuid.uuid4())
for fn in file_set:
    print
    "Processing ", fn
    with open(fn, 'rb', 0) as a:
        with open(temp_fname, 'w') as b:
            rc = subprocess.call(["./fix_temp_code"], stdin=a, stdout=b)
            if rc:
                print
                "FAILED ", rc
                continue
            rc = subprocess.call(["mv", temp_fname, fn])
            if rc:
                print
                "FAILED ", rc
            else:
                print
                "SUCCESS"
